### ISSUE TITLE
PlayStation 4 DS4 index 16 "PS button" support 

### ISSUE THREAD

**Issue by foxnewsnetwork** [ericlathrop/html5-gamepad#11]
# Background
If you hook up a DS4 to your computer and visit http://html5gamepad.com/ , you'll see that index: 16 (if you're on iOS) lights up when you push the PS button 

![ds4-ps-btn](https://cloud.githubusercontent.com/assets/1010423/25398762/f7bd84a8-29a1-11e7-9930-6b7b86815a19.jpg)
* (1 billion hours in paint.exe)

However, in the current mappings, support for button 16 doesn't exist. 

# Proposal
Implement support for 16 and call it something like:

```json
"special": { 
  "index": 16
}
```
or perhaps

```json
"logo": { 
  "index": 16
}
```

If you're okay with this, I can open a PR

**Comment by ericlathrop** [comment]
It should probably be mapped as "home", which would match the current xbox mappings. A PR would be welcome. Thanks!

**Comment by foxnewsnetwork** [comment]
Okay sounds good. On the DS4, "home" is actually received from pushing the touchpad which is "index": 17
