### ISSUE TITLE
This seems to break on chrome 55

### ISSUE THREAD

**Issue by wdjungst** [ericlathrop/html5-gamepad#6]
function transformGamepad(threshold, gamepad) {
  var gp = {
    id: gamepad.id,
    buttons: {},
    axes: {}
  };

gamepad is undefined

**Comment by ericlathrop** [comment]
I think chrome recently made some changes to how gamepads work. Can you try out the `dynamic-mapping` branch to see if it works for you? It's going to become the next version, but it does have breaking changes to the API. I spent a lot of time on it last weekend testing a lot of different controllers across multiple browsers. The README hasn't been updated in that branch yet.

**Comment by ericlathrop** [comment]
This should be fixed now.
